# Generated by Django 3.2.9 on 2021-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotate', '0002_auto_20211129_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
