# Generated by Django 3.2.9 on 2021-11-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotate', '0003_images_image_annotations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_annotations',
        ),
    ]
